ARCHS = arm64
TARGET = iphone:clang:latest:14.0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WizardBypass

WizardBypass_FILES = WizardBypass.x
WizardBypass_CFLAGS = -fobjc-arc
WizardBypass_FRAMEWORKS = UIKit Foundation
WizardBypass_LDFLAGS = -Wl,-undefined,dynamic_lookup

include $(THEOS_MAKE_PATH)/tweak.mk
